### ISSUE TITLE
GAVariant missing "quality" and "filter"

### ISSUE THREAD

**Issue by jrobinso** [ga4gh/ga4gh-schemas#219]
Hi,  the v0.5.1 GAVariant specification does not list the "filter" and "quality" fields,  which are part of the VCF specification.   However, variants I fetch from https://www.googleapis.com/genomics/v1beta2/variants/search do include them.   Is this a mistake in the specification,  or are these fields no longer required?

**Comment by johntbates** [comment]
Hi, Jim.

You're correct: the GAVariant schema lacks those fields, despite the fact that the Google v1beta2 implementation returns them.  This appears to be an oversight in the specification and I'll be submitting a pull request to address this.  Thank you for pointing it out!

-John Bates

**Comment by skeenan** [comment]
This has been dormant since January. Closing in 2 days.

**Comment by jeromekelleher** [comment]
There is still a PR open (#220) for this, so I don't think we should close it. Perhaps we should ping those involved and try to get the PR updated?

**Comment by skeenan** [comment]
Thanks @jeromekelleher I've pinged @johntbates in https://github.com/ga4gh/schemas/pull/220

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/ga4gh-schemas/pull/826
