### ISSUE TITLE
Add release process

### ISSUE THREAD

**Issue by david4096** [ga4gh/ga4gh-schemas#753]
Now that we coordinate releases of packages to pypi, we need to provide documentation for performing a release. Notably, python packages are versioned separately from the protocol currently. Let's set the pip packages version to match the protocol version. This is similar to what the protocol buffers python package does, in that the version attempts to match the protocol, `3.1.0`, but sometimes post release packages to PyPi are made, as in `3.1.0.post1`.

**Comment by kozbo** [comment]
I have created a document that describes our plan. After internal review I will publish it to the ga4gh/server wiki, and then we can close this issue.

**Comment by david4096** [comment]
Related https://github.com/ga4gh/schemas/issues/844

**Comment by kozbo** [comment]
@dcolligan We can close this with an update to the development release section (post release) that describes what was done for this release.

**Comment by dcolligan** [comment]
Fixed in #1630
