### ISSUE TITLE
Geodata object

### ISSUE THREAD

**Issue by mbaudis** [ga4gh/ga4gh-schemas#771]
This issue is to get feedback on how to implement geodata support in the GA4GH schema. Principle options would be:

* adoption of the [RFC 7946](https://tools.ietf.org/html/rfc7946) "GeoJSON" specification (would this have to be replicated in the schema?)
* creation of a generic prototype object in `metadata.proto`, representing a limited subset of GeoJSON attributes (i.e. point object; see [this AVRO representation](https://github.com/ga4gh/schemas/blob/metadata/src/main/resources/avro/metadata.avdl#L48) in the deprecated metadata development branch)

Feedback/comments appreciated!

**Comment by david4096** [comment]
Leaving this here for now https://github.com/mapbox/geobuf

Do you have and example of data to be interchanged that includes geospatial values?

**Comment by mbaudis** [comment]
David @david4096, 

* sure there are a number of ways to include/reference/encode geodata; but I rather would reference/track a standard (one could use the Google maps API specs, too, but I rather prefer IETF or ISO to some commercial implementer)
* overhead is minimal for points in GeoJSON (in contrast to country/regional borders - that's overdoing denormalisation, even for me)
* as for examples: every GEO samples (tries to) include the submitter's city ... at least, which is a pain if done in free text (Paris, Texas ...)
* as other example, for arraymap.org | progenetix.org, we attempt to map/refine to get geographic sample provenance
* and for non human samples, there are e.g. these [environmental sampling](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.0050077) projects 

So, definitely, many/most first line data objects (biosample, individual, experiment ...) can make use of geodata; and this should be provided in a format maintained outside of GA4GH (like ISO8601 for times).

**Comment by david4096** [comment]
@mbaudis Agreed on all accounts. I linked to mapbox's geobuf, which is a compression of geojson using protocol buffers. My hope is that we can leverage their work to rapidly iterate on this feature.

Let's constrain this issue to simply finding an interchange model for these data. If queries become necessary for basic interchange, we can address that feature in those services. For now, we ought to be able to add a GeoJSON-like field to the messages you've mentioned. Here is a link to [mapbox's geobuf proto](https://github.com/mapbox/geobuf/blob/master/geobuf.proto).

**Comment by david4096** [comment]
Should this be added as a named field to any messages? The location of the sequencing center for an Experiment message?

**Comment by mbaudis** [comment]
Could be a named field, if only considering one per record; or carry a label (e.g. listing multiple contacts, collaborators ...).

**Comment by mbaudis** [comment]
Please follow up on this in PR https://github.com/ga4gh/ga4gh-schemas/pull/864 .
