### ISSUE TITLE
GeoLocation attributes names

### ISSUE THREAD

**Issue by mcourtot** [ga4gh/ga4gh-schemas#882]
https://github.com/ga4gh/ga4gh-schemas/blob/metadata-integration/src/main/proto/ga4gh/common.proto#L175

@mbaudis: should we rename geo_label and geo_precision to label and precision respectively? Other GeoLocation attributes don't have the geo_ prefix.

**Comment by mbaudis** [comment]
Done. Actually had the same idea yesterday, when looking at the names (for the meeting doc ...).
